spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/flyway_db
    username: flyway_user
    password: 2381012
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  flyway:
    enabled: true
    locations: classpath:db.migration #filesystem:db.migration
    baseline-on-migrate: true
    # repeatable-sql-migration-prefix: V
    validate-on-migrate: true
myapp:
  api:
    urlFilmsById: ${API_URL_FILM_BY_ID}
    urlFilmsTypedCollections: ${API_URL_FILMS_BY_TYPE_COLLECTIONS}
    name: ${HEADER_NAME}
    token: ${HEADER_VALUE}